name: CI


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 6 * * *  # Daily 6AM UTC build

jobs:
  test:
    permissions:
      contents: read # to fetch code (actions/checkout) (I'll implement add package uploading later)

    strategy:
      matrix:
        pyver: ['3.9', '3.10', '3.11', '3.12', '3.13']
        no-extensions: ['', 'Y']
        os: [ubuntu, macos, windows]
        experimental: [false]
        exclude:
          - os: macos
            no-extensions: 'Y'
          - os: windows
            no-extensions: 'Y'
        # include:
          # NOT READY!
          # - pyver: pypy-3.9
          #   no-extensions: 'Y'
          #   os: ubuntu
          #   experimental: false
          # - os: ubuntu
          #   pyver: "3.14"
          #   experimental: true
          #   no-extensions: 'Y'
      fail-fast: true
    
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Python ${{ matrix.pyver }}
      id: python-install
      uses: actions/setup-python@v5
      with:
        allow-prereleases: true
        python-version: ${{ matrix.pyver }}
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Cache PyPI
      uses: actions/cache@v4.2.4
      with:
        key: pip-ci-${{ runner.os }}-${{ matrix.pyver }}-${{ matrix.no-extensions }}-${{ hashFiles('requirements/*.txt') }}
        path: ${{ steps.pip-cache.outputs.dir }}
        restore-keys: |
            pip-ci-${{ runner.os }}-${{ matrix.pyver }}-${{ matrix.no-extensions }}-
    - name: Update pip, wheel, setuptools, build, twine
      run: |
        python -m pip install -U pip wheel setuptools build twine
    - name: Install dependencies
      run: |
        python -m pip install -r requirements/pytest.txt

    - name: Install self
      run: python -m pip install -e .

    - name: Run PyTests
      env:
        COLOR: yes
        PIP_USER: 1
      run: pytest
      shell: bash
    